server:
  port: 8991
  servlet:
    context-path: /arPcStaffWeb


logging:
  config: classpath:logback-spring.xml

log:
  localLogPath: ../log/staffWebLog
  cloudLogPath: staffWebLog
spring:
  profiles:
#    active: dev
    active: prod