server:
  port: 8990
  servlet:
    context-path: /arPcStaffWeb

spring:
  redis:
    database: 3
    password: webredis
    host: 123.60.71.74
    timeout: 5000
    jedis:
      pool:
        min-idle: 1
        max-idle: 5
        max-active: 5
        max-wait: -1
logging:
  config: classpath:logback-spring.xml

log:
  localLogPath: ../log/routerLog
  cloudLogPath: routerLog