spring:
  datasource:
    username: username
    password: pwd
    url: jdbc:mysql://localhost:3306/ar?serverTimezone=Asia/Shanghai
    hikari:
      max-lifetime: 100000
  redis:
    host: host
    password: pwd
    database: 3


#  jackson:
#    default-property-inclusion: non_null

mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml

